### ISSUE TITLE
Callback url in file upload api

### ISSUE THREAD

**Issue by fllprbt** [Smartling/api-sdk-nodejs#107]
Similarly to the batches, the file upload api should have a `setCallbackUrl` helper.

Also, we do it before sending but you might want to consider encoding callback urls wherever you send them. Or do you see no reason?

**Comment by PavelLoparev** [comment]
Hi @fllprbt, here is a PR that addresses this issue.

> Also, we do it before sending but you might want to consider encoding callback urls wherever you send them. Or do you see no reason?
I don't have strong opinion on do we need to do it inside sdk or caller should do this. I think I will stick to the what we already have in sdk (sdk doesn't encode callbackUrl value)

**Comment by dimitrystd** [comment]
I don't think we should explicitly encode it. Client code is responsible for passing a valid URL. SDK is responsible for correctly putting in it into the HTTP payload, which is done by HTTP lib.

**Comment by fllprbt** [comment]
I 've been into some similar contexts lately and I 've seen it being a requirement from consumers. So I will indeed close the ticket for now but leaving it up to you on how to proceed. Thanks!

**Comment by PavelLoparev** [comment]
Rolled ou `2.11.0` release.
