### ISSUE TITLE
npm install requires access to artifactory

### ISSUE THREAD

**Issue by chemdrew** [Smartling/api-sdk-nodejs#66]
when I clone the project and then run `npm i` I receive the error below when npm attempts to install @smartling/eslint-config-smartling.

Looks like it's behind a firewall

<img width="1075" alt="Screen Shot 2022-04-06 at 10 22 23 AM" src="https://user-images.githubusercontent.com/8684337/162032398-3a414414-f9eb-4629-8df3-9fee0cb09048.png">

**Comment by dimitrystd** [comment]
Fixed in 1.2.4.
