### ISSUE TITLE
CustomFieldDto is missing fieldValue

### ISSUE THREAD

**Issue by kyle-heddon** [Smartling/api-sdk-nodejs#72]
I get typescript errors when trying to access a customField's fieldValue:

```
const jobDetails = await jobsApi.getJob(projectId, translationJobUid);
const customField = jobDetails.customFields.find(findMyCustomFieldByFieldUid);
if (customField) {
  const value = customField.fieldValue; // TS2339: Property 'fieldValue' does not exist on type 'CustomFieldDto'.
  console.log({value});
}
```

This happens because the CustomFieldDto interface is missing `fieldValue`.

While you can work around the issue with a `@ts-ignore` comment, it doesn't help with discoverability.

**Comment by PavelLoparev** [comment]
Hi @kyle-heddon, thanks for the PR. Released https://www.npmjs.com/package/smartling-api-sdk-nodejs

**Comment by kyle-heddon** [comment]
Thanks for the quick turnaround!
