### ISSUE TITLE
uploadFile failed due to node.js version issue

### ISSUE THREAD

**Issue by iPeng6** [Smartling/api-sdk-nodejs#80]
my local node.js version is v18.12.1 , it will display this issue
```bash
TypeError: Cannot set property closed of #<Readable> which has only a getter
      at new ReadStream (/Users/user/work/fe-tools/node_modules/string-to-file-stream/index.js:57:15)
      at string2fileStream (/Users/user/work/fe-tools/node_modules/string-to-file-stream/index.js:227:10)
      at UploadFileParameters.setFileContent (/Users/user/work/fe-tools/node_modules/smartling-api-sdk-nodejs/built/api/files/params/upload-file-parameters.js:47:62)
```
but when I switch to version v16.16 , it's fine.
dig into the source code, It seems we can't set the property `closed` in higher node.js version

```js
// node_modules/string-to-file-stream/index.js:57,15
const { Readable } = require('stream');
function ReadStream(input, options) {
  // ...
  Readable.call(this, options);
 // ...
  this.pos = undefined;
  this.bytesRead = 0;
  this.closed = false; // ❌
}
```

**Comment by wr-iloubser** [comment]
I am getting the same issue - is there any known workaround for this ?

**Comment by wr-iloubser** [comment]
Nvm, I just added a resolution for `"string-to-file-stream": "2.0.0"` in my package json as it's resolved in latest version. That seemed to fix it :)

**Comment by PavelLoparev** [comment]
Hi @iPeng6 and @wr-iloubser, this PR should fix the issue https://github.com/Smartling/api-sdk-nodejs/pull/87
