### ISSUE TITLE
closeJob API

### ISSUE THREAD

**Issue by SnigdhaSinha-signifyd** [Smartling/api-sdk-nodejs#81]
There is a `closeJob` API, but it doesn't exist within the jobs API for the node sdk. Can this be added? https://api-reference.smartling.com/preview/jobs-2122-job-schedule/#tag/Jobs/operation/closeJob

**Comment by SnigdhaSinha-signifyd** [comment]
I put up a PR to address this https://github.com/Smartling/api-sdk-nodejs/pull/82

**Comment by dimitrystd** [comment]
Sorry, it took longer. Released as 1.5.2.
