### ISSUE TITLE
jobs API - upload file

### ISSUE THREAD

**Issue by fllprbt** [Smartling/api-sdk-nodejs#89]
Hi, 

I 'd be interested in implementing the *Smartling API Flow - Files & Jobs* depicted in the [API Flow Example](https://help.smartling.com/hc/en-us/articles/360007812713-API-Flow-Example) of docs.

I don't seem to be able to find some helper like the one of the batches to either 

* create a new job with a list of file URIs or 
* add files to job after it is being created. 

Is this not implemented or I miss the way of working? Thanks!

**Comment by fllprbt** [comment]
Nope, I want to add a file directly to a job and not use the batches API at all since I don't have a use case for batches in the first place.

That's the behaviour I am talking about in the api: https://api-reference.smartling.com/#tag/Jobs/operation/addFileToJob

**Comment by dimitrystd** [comment]
This is not something I would recommend. I would advise you to think about Job Batches and speak with your CSM\SA. He can arrange a call with the Smartling tech team where you can discuss your goals and architecture.

You are right, SDK doesn't include this method. You may submit your PR. Or we will place this issue in backlog and implement it in the future. So far, we don't have an ETA.

**Comment by fllprbt** [comment]
Check, I will open a PR in a bit. We have only a single file with minor +- diffs and I would like to avoid all the batches related gymnastics.

**Comment by fllprbt** [comment]
Could you please add me in the project?
```
ERROR: Permission to Smartling/api-sdk-nodejs.git denied to fllprbt.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by fllprbt** [comment]
Closing the issue in favour of https://github.com/Smartling/api-sdk-nodejs/pull/91
