### ISSUE TITLE
Authorize job endpoint support / job.callbackUrl parameter

### ISSUE THREAD

**Issue by fllprbt** [Smartling/api-sdk-nodejs#92]
Hi again. I have some extra usage needs to encapsulate some calls. Both are for automation purposes. In my use case, we want to streamline as much as possible (devs own the content) the manual work. So, I 'd be interested in:

* https://api-reference.smartling.com/#tag/Jobs/operation/authorizeJob => adding this helper
* allow passing `callbackUrl` param when a job is created or by adding an [update job](https://api-reference.smartling.com/#tag/Jobs/operation/updateJob) helper.

Please let me know if you are ok with supporting these endpoints/configuration to see how to proceed.

Thanks!

**Comment by dimitrystd** [comment]
Hi. Please submit a pull request. We are happy to accept anything in the public API documentation.

However, I would repeat my recommendation to have your architecture reviewed by a Smartling solution architect. I would also recommend learning:
- Understand the distinction between callback for Job and callback for File.
- Consider how your integration will work if file strings are spread across two or more jobs.
- Will you deliver translations if not all strings have been authorized?
- What about pre-published translations.

Using jobs API directly may not cover all cases.

**Comment by fllprbt** [comment]
Thanks for sharing, discussed them 👍🏼 

Closing this issue, since I am opening myself the MRs => https://github.com/Smartling/api-sdk-nodejs/pull/93

Could I have a review to avoid stacking up multiple new things in a single MR?

**Comment by fllprbt** [comment]
Thanks for sharing, discussed them 👍🏼

Closing this issue, since I am opening myself the MRs => https://github.com/Smartling/api-sdk-nodejs/pull/93

@PavelLoparev could you please review to avoid stacking up multiple additions in a single MR?
