### ISSUE TITLE
Files API - List Recently Published Files

### ISSUE THREAD

**Issue by zanderson3j** [Smartling/api-sdk-nodejs#97]
Hi,

I am using this SDK for file translations. I was hoping to use this endpoint to check for recently published files in case the callback fails that notifies us that a file translation is complete.

https://api-reference.smartling.com/#tag/Files/operation/getRecentlyPublishedFilesList

Is this something that can be added to this sdk, or should I use the api directly?

Thanks!

**Comment by dimitrystd** [comment]
Hi, you are welcome to contribute via pull request. If you consider this, please use codestyle similar to existing classes, and don't forget about tests. Thanks

**Comment by zanderson3j** [comment]
Hey @dimitrystd, I create a PR to add this https://github.com/Smartling/api-sdk-nodejs/pull/99
